# cluster_config.yml - cluster configuration
__default__:
  account: donczew-lab
  partition: serial
  time: "08:00:00"
  cpus-per-task: 2
  mem: "16G"
  output: logs/slurm-%x.%A.%a.log
  error: logs/slurm-%x.%A.%a.err

# ------------------------------------------------------------------------------
# Raw Quality Control
# ------------------------------------------------------------------------------
fastqc_raw:
  cpus-per-task: 4
  mem: "32G"
  cores: 4
  time: "02:00:00"
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

multiqc_raw:
  cpus-per-task: 4
  mem: "32G"
  cores: 4
  time: "02:00:00"
  name: "{rule}"
  output: logs/{rule}.out
  error: logs/{rule}.err
  
# ------------------------------------------------------------------------------
# UMIs processing with fastp
# ------------------------------------------------------------------------------
process_umis:
  cpus-per-task: 4
  mem: "32G"
  cores: 4
  time: "02:00:00"
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

# ------------------------------------------------------------------------------
# Adapter Trimming with BBDuk
# ------------------------------------------------------------------------------
trim_adapters:
  cpus-per-task: 8
  mem: "32G"
  cores: 8
  time: "02:00:00"
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

# ------------------------------------------------------------------------------
# Trimmed Quality Control
# ------------------------------------------------------------------------------
fastqc_trimmed:
  cpus-per-task: 4
  mem: "32G"
  cores: 4
  time: "02:00:00"
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

multiqc_trimmed:
  cpus-per-task: 4
  mem: "32G"
  cores: 4
  time: "02:00:00"
  name: "{rule}"
  output: logs/{rule}.out
  error: logs/{rule}.err

# ------------------------------------------------------------------------------
# SLAMDUNK - main processing step
# ------------------------------------------------------------------------------
slamdunk_all:
  cpus-per-task: 24
  mem: "64G"
  cores: 16
  time: "08:00:00"
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

slamdunk_count:
  cpus-per-task: 24
  mem: "64G"
  cores: 16
  time: "08:00:00"
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

# ------------------------------------------------------------------------------
# Alleyoop (analysis on SLAM-Seq results)
# ------------------------------------------------------------------------------
alleyoop_rates:
  cpus-per-task: 24
  mem: "64G"
  cores: 16
  time: "04:00:00"
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

alleyoop_tccontext:
  cpus-per-task: 24
  mem: "64G"
  cores: 16
  time: "04:00:00"
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

alleyoop_utrrates:
  cpus-per-task: 24
  mem: "64G"
  cores: 16
  time: "04:00:00"
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

alleyoop_snpeval:
  cpus-per-task: 24
  mem: "64G"
  cores: 16
  time: "04:00:00"
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

alleyoop_summary_onetcreadcount:
  cpus-per-task: 24
  mem: "64G"
  cores: 16
  time: "04:00:00"
  name: "{rule}"
  output: logs/{rule}.out
  error: logs/{rule}.err

alleyoop_summary_twotcreadcount:
  cpus-per-task: 24
  mem: "64G"
  cores: 16
  time: "04:00:00"
  name: "{rule}"
  output: logs/{rule}.out
  error: logs/{rule}.err

alleyoop_merge_totalreadcount:
  cpus-per-task: 8
  mem: "32G"
  cores: 8
  time: "04:00:00"
  name: "{rule}"
  output: logs/{rule}.out
  error: logs/{rule}.err

alleyoop_merge_onetcreadcount:
  cpus-per-task: 8
  mem: "32G"
  cores: 8
  time: "04:00:00"
  name: "{rule}"
  output: logs/{rule}.out
  error: logs/{rule}.err

alleyoop_merge_twotcreadcount:
  cpus-per-task: 8
  mem: "32G"
  cores: 8
  time: "04:00:00"
  name: "{rule}"
  output: logs/{rule}.out
  error: logs/{rule}.err

counts_and_normfactors:
  cpus-per-task: 4
  mem: "32G"
  cores: 4
  time: "01:00:00"
  name: "{rule}"
  output: logs/{rule}.out
  error: logs/{rule}.err

alleyoop_tcperreadpos:
  cpus-per-task: 8
  mem: "32G"
  cores: 8
  time: "04:00:00"
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

alleyoop_tcperutrpos:
  cpus-per-task: 8
  mem: "32G"
  cores: 8
  time: "04:00:00"
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

alleyoop_dump:
  cpus-per-task: 8
  mem: "32G"
  cores: 8
  time: "04:00:00"
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

# ------------------------------------------------------------------------------
# MultiQC on Slam Dunk output
# ------------------------------------------------------------------------------
multiqc_slamdunk:
  cpus-per-task: 4
  mem: "32G"
  cores: 4
  time: "02:00:00"
  name: "{rule}"
  output: logs/{rule}.out
  error: logs/{rule}.err


# ------------------------------------------------------------------------------
# SPIKE IN Rules
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# SLAMDUNK - main processing step
# ------------------------------------------------------------------------------
slamdunk_all_spikeIn:
  cpus-per-task: 24
  mem: "64G"
  cores: 16
  time: "08:00:00"
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

slamdunk_count_spikeIn:
  cpus-per-task: 24
  mem: "64G"
  cores: 16
  time: "08:00:00"
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

# ------------------------------------------------------------------------------
# Alleyoop (analysis on SLAM-Seq results)
# ------------------------------------------------------------------------------
alleyoop_rates_spikeIn:
  cpus-per-task: 24
  mem: "64G"
  cores: 16
  time: "04:00:00"
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

alleyoop_tccontext_spikeIn:
  cpus-per-task: 24
  mem: "64G"
  cores: 16
  time: "04:00:00"
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

alleyoop_utrrates_spikeIn:
  cpus-per-task: 24
  mem: "64G"
  cores: 16
  time: "04:00:00"
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

alleyoop_snpeval_spikeIn:
  cpus-per-task: 24
  mem: "64G"
  cores: 16
  time: "04:00:00"
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

alleyoop_summary_onetcreadcount_spikeIn:
  cpus-per-task: 24
  mem: "64G"
  cores: 16
  time: "04:00:00"
  name: "{rule}"
  output: logs/{rule}.out
  error: logs/{rule}.err

alleyoop_summary_twotcreadcount_spikeIn:
  cpus-per-task: 24
  mem: "64G"
  cores: 16
  time: "04:00:00"
  name: "{rule}"
  output: logs/{rule}.out
  error: logs/{rule}.err

alleyoop_merge_totalreadcount_spikeIn:
  cpus-per-task: 8
  mem: "32G"
  cores: 8
  time: "04:00:00"
  name: "{rule}"
  output: logs/{rule}.out
  error: logs/{rule}.err

alleyoop_merge_onetcreadcount_spikeIn:
  cpus-per-task: 8
  mem: "32G"
  cores: 8
  time: "04:00:00"
  name: "{rule}"
  output: logs/{rule}.out
  error: logs/{rule}.err

alleyoop_merge_twotcreadcount_spikeIn:
  cpus-per-task: 8
  mem: "32G"
  cores: 8
  time: "04:00:00"
  name: "{rule}"
  output: logs/{rule}.out
  error: logs/{rule}.err

alleyoop_tcperreadpos_spikeIn:
  cpus-per-task: 8
  mem: "32G"
  cores: 8
  time: "04:00:00"
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

alleyoop_tcperutrpos_spikeIn:
  cpus-per-task: 8
  mem: "32G"
  cores: 8
  time: "04:00:00"
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

alleyoop_dump_spikeIn:
  cpus-per-task: 8
  mem: "32G"
  cores: 8
  time: "04:00:00"
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

# ------------------------------------------------------------------------------
# MultiQC on Slam Dunk output
# ------------------------------------------------------------------------------
multiqc_slamdunk_spikeIn:
  cpus-per-task: 4
  mem: "32G"
  cores: 4
  time: "02:00:00"
  name: "{rule}"
  output: logs/{rule}.out
  error: logs/{rule}.err
