# ==============================================================================
# SAMPLES FILE
# ==============================================================================
samples_csv: "config/samples.csv"

# ==============================================================================
# PRIMARY GENOME & BED FILE PATHS (S. cerevisiae default)
# ==============================================================================
primary_genome: "/hpc-prj/donczew/genomic_resources/Scerevisiae_GCF_000146045.2/SGD_R64-3-1_genome.fna"              # Genome reference for SLAMDUNK
primary_bed: "/hpc-prj/donczew/genomic_resources/Scerevisiae_GCF_000146045.2/Scerevisiae_R64-3-1_gene3utr.bed"       # Gene + 3-prime UTR BED file

# ==============================================================================
# TOGGLE ON/OFF SPIKE-IN (S. pombe default)
# ==============================================================================
use_spikein: false
spikein_genome: "/hpc-prj/donczew/genomic_resources/Spombe_GCF_000002945.1/NCBI_ASM294v2_genome.fna"
spikein_bed: "/hpc-prj/donczew/genomic_resources/Spombe_GCF_000002945.1/Spombe_ASM294v2_gene3utr.bed"

# ==============================================================================
# FASTP PARAMETERS
# ==============================================================================
umi_loc: "read2"
umi_len: 12

# ==============================================================================
# TOGGLE ON/OFF TRIM GALORE (false = BBDuk | true = Trim Galore)
# ==============================================================================
use_trim_galore: false
# BBDuk adapter file
bbmap_ref: "/hpc-prj/donczew/genomic_resources/bbmap/truseq_universal_adapters.fa"
# Trim Galore parameters
stringency: 3
length: 10

# ==============================================================================
# SLAMDUNK PARAMETERS
# ==============================================================================
trim_5p: 5
topn: 100
multimap: true
min_coverage: 10
var_fraction: 0.8
max_read_length: 151
min_base_qual: 26
skip_sam: true

# ==============================================================================
# SOFTWARE MODULE VERSIONS
# ==============================================================================
fastqc: "fastqc/0.12.1"
multiqc: "multiqc/1.21"
fastp: "fastp/0.23.2"
bbmap: "bbmap/39.06"
trim_galore: "trim_galore/0.6.7"
slamdunk: "slamdunk/0.4.3"
nextgenemap: "nextgenemap/0.5.5"
samtools: "samtools/1.18"
python: "python/3.10.2"
R: "R/4.4.1-mkl"
varscan: "varscan/2.4.5"
